# vagrant_hosts.yml
#
# List of hosts to be created by Vagrant. For more information about the
# possible settings, see the documentation at
# <https://github.com/bertvv/ansible-skeleton>

# ##########################################################################
# Example host definition
# ##########################################################################
# - name: srv002
#   box: bento/fedora-28
#   memory: 2048
#   cpus: 2
#   forwarded_ports:
#     - host: 8080
#       guest: 80
#     - host: 8443
#       guest: 443
#   networks:
#     - type: private_network
#       attributes:
#         ip: 10.10.5.201
#         netmask: 255.255.255.0
#     - type: public_network
#       attributes:
#         type: "dhcp"
#         name: "homenet"
#   synced_folders:
#     - src: test
#       dest: /tmp/test
#     - src: www
#       dest: /var/www/html
#       options:
#         :create: true
#         :owner: root
#         :group: root
#         :mount_options: ['dmode=0755', 'fmode=0644']
#   playbook: srv002.yml

---
- name: k8s-ca
  cpus: 1
  memory: 1024
  forwarded_ports:
    - host: 2002
      guest: 22
  group: ca
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.2

- name: k8s-lb
  cpus: 1
  memory: 1024
  forwarded_ports:
    - host: 2011
      guest: 22
  group: loadbalancers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.11

- name: k8s-m1
  cpus: 1
  memory: 1024
  forwarded_ports:
    - host: 2021
      guest: 22
  group: controllers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.21

- name: k8s-m2
  cpus: 1
  memory: 1024
  forwarded_ports:
    - host: 2022
      guest: 22
  group: controllers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.22

- name: k8s-w1
  forwarded_ports:
    - host: 2031
      guest: 22
  group: workers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.31

- name: k8s-w2
  forwarded_ports:
    - host: 2032
      guest: 22
  group: workers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.32

- name: k8s-w3
  forwarded_ports:
    - host: 2033
      guest: 22
  group: workers
  networks:
    - type: private_network
      attributes:
        ip: 192.168.5.33
